[package]
name = "lingua-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "lingua_ffi"
crate-type = ["cdylib"]

[dependencies]
lingua = "1.6.0"
libc = "0.2"

[build-dependencies]
cbindgen = "0.24" 
